benchmark_dirpath: ./genbench3d_data/
glide_working_dir: None
results_dir: ./genbench3d_data/results/
test_set_dir: ./genbench3d_data/test_set/

pocket_distance_from_ligand: 5.0 # Angstrom

bin:
  prepare_receptor_bin_path: './ADFRsuite/bin/prepare_receptor' # https://ccsb.scripps.edu/adfr/downloads/
  glide_path: '/usr/local/shared/schrodinger/current/glide'
  structconvert_path: '/usr/local/shared/schrodinger/current/utilities/structconvert'

data:
  ligboundconf_name: 'LigBoundConf'
  ligboundconf_path: './genbench3d_data/S2_LigBoundConf_minimized.sdf' # https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.0c01197/suppl_file/ci0c01197_si_002.zip
  csd_drug_subset_path: './genbench3d_data/CSD_Drug_Subset.gcd' # https://ars.els-cdn.com/content/image/1-s2.0-S0022354918308104-mmc2.zip
  minimized_path: './genbench3d_data/paper_reproduce/minimized/'
  test_set_path: './genbench3d_data/test_set/'

genbench3d:
  minimum_pattern_values: 50
  tfd_threshold: 0.2
  q_value_threshold: 0.001
  steric_clash_safety_ratio: 0.75
  maximum_ring_plane_distance: 0.1 # Angstrom
  consider_hydrogens: False
  include_torsions_in_validity3D: False
  add_minimized_docking_scores: True
  overwrite_results: True

models:
  targetdiff_results_filepath: './genbench3d_data/paper_reproduce/targetdiff/targetdiff_vina_docked.p'
  threedsbdd_gen_dirpath: './genbench3d_data/paper_reproduce/AR/test_set/'
  pocket2mol_gen_dirpath: './genbench3d_data/paper_reproduce/Pocket2Mol/test_set/'
  diffsbdd_gen_dirpath:  './genbench3d_data/paper_reproduce/DiffSBDD/crossdocked_fullatom_joint/'
  ligan_gen_dirpath: './genbench3d_data/paper_reproduce/LiGAN/molecules/'
  resgen_gen_dirpath: './genbench3d_data/paper_reproduce/ResGen/test_set/'

minimization:
  distance_constraint: 1.0 # Angstrom
  n_steps: 1000

vina:
  scoring_function: 'vina'
  size_border: 35 # Angstrom
  n_cpus: 4
  seed: 2023